"""Assignment 1 - Grocery Store Events (Task 2)

CSC148 Winter 2024
Department of Computer Science,
University of Toronto

This code is provided solely for the personal and private use of
students taking the CSC148 course at the University of Toronto.
Copying for purposes other than this use is expressly prohibited.
All forms of distribution of this code, whether as given or with
any changes, are expressly prohibited.

All of the files in this directory are
Copyright (c) Jonathan Calver, Diane Horton, Sophia Huynh, Joonho Kim and
Jacqueline Smith.

Module Description:

When you are done Task 2, this file should contain all the classes
necessary to model the different kinds of events in the simulation.
"""
from __future__ import annotations

from io import StringIO
from typing import TextIO
from store import GroceryStore, Customer, Item, NoAvailableLineError


class Event:
    """An event in our grocery store simulation.

    Events have an ordering based on the event timestamp. For any two events
    e1 and e2, e1 < e2 iff event e1 has a timestamp that is less than event e2.
    This signifies that e1 happens before e2.

    This is an abstract class and should not be instantiated.

    Attributes:
    - timestamp: The time when this event occurs.

    Representation Invariants:
    - self.timestamp >= 0
    """

    timestamp: int

    def __init__(self, timestamp: int) -> None:
        """Initialize an Event with a given timestamp.

        Preconditions:
            - timestamp >= 0

        >>> Event(7).timestamp
        7
        """
        self.timestamp = timestamp

    # The following three methods allow for comparison of Event instances
    # using the standard comparison operators, such as ==, <, and <=.
    # All methods simply perform the desired comparison on the 'timestamp'
    # attribute of the two events.
    def __eq__(self, other: Event) -> bool:
        """Return whether this Event is equal to <other>.

        Two events are equal iff they have the same timestamp.

        >>> first = Event(1)
        >>> second = Event(2)
        >>> first == second
        False
        >>> second.timestamp = first.timestamp
        >>> first == second
        True
        """
        return self.timestamp == other.timestamp

    def __lt__(self, other: Event) -> bool:
        """Return True iff this Event is less than <other>.

        >>> first = Event(1)
        >>> second = Event(2)
        >>> first < second
        True
        >>> second < first
        False
        """
        return self.timestamp < other.timestamp

    def __le__(self, other: Event) -> bool:
        """Return True iff this Event is less than or equal to <other>.

        >>> first = Event(1)
        >>> second = Event(2)
        >>> first <= first
        True
        >>> first <= second
        True
        >>> second <= first
        False
        """
        return self.timestamp <= other.timestamp

    def do(self, store: GroceryStore) -> list[Event]:
        """Perform this event as specified in the A1 handout, and return any
        events generated by doing so.
        """
        raise NotImplementedError


# TODO: create subclasses for the different types of events below.
class CustomerArrival(Event):
    """A customer arrives at the checkout area ready to join a line and
    check out.

    Attributes:
    - customer: The arriving customer
    """

    timestamp: int
    customer: Customer

    def __init__(self, timestamp: int, c: Customer) -> None:
        """Initialize a CustomerArrival event with the given <timestamp>
        and customer <c>.

        If the customer's arrival time is None, set it now to record
        the fact that this is the time when they first arrived at the
        checkout area. (This is the start of their waiting time.)

        Preconditions:
        - timestamp >= 0
        """
        Event.__init__(self, timestamp)
        self.customer = c
        self.timestamp = timestamp
        if self.customer.arrival_time is None:
            self.customer.arrival_time = timestamp

    def do(self, store: GroceryStore) -> list[Event]:
        """Perform this CustomerArrival event as specified in the A1 handout,
        and return any events generated by doing so.
        """
        events = []
        try:
            line_number = store.enter_line(self.customer)
            if store.first_in_line(line_number) is self.customer:
                events.append(
                    CheckoutStarted(self.timestamp, line_number)
                )  # must be first in line for this to happen
            else:
                future_timestamp = self.timestamp + 1
                events.append(CustomerArrival(future_timestamp, self.customer))
        except NoAvailableLineError:
            # No available line, schedule a new CustomerArrival event in the future
            future_timestamp = self.timestamp + 1
            events.append(CustomerArrival(future_timestamp, self.customer))
        return events


class CheckoutStarted(Event):
    """A customer starts the checkout process in a particular checkout line.

    Attributes:
    - line_number: The number of the checkout line.
    """

    timestamp: int
    line_number: int

    def __init__(self, timestamp: int, line_number: int) -> None:
        """Initialize a CheckoutStarted event with the given <timestamp>
        and <line_number>.

        Preconditions:
        - timestamp >= 0
        - line_number >= 0
        """
        Event.__init__(self, timestamp)
        self.timestamp = timestamp
        self.line_number = line_number

    def do(self, store: GroceryStore) -> list[Event]:
        """Perform this CheckoutStarted event as specified in the A1 handout,
        and return any events generated by doing so.
        """
        line = store.lines[self.line_number]
        events = []
        line_number = self.line_number
        # checkout_time = line.first_in_line().item_time()
        checkout_time = store.next_checkout_time(line_number)  # Gives right for self_serve

        # if checkout_time == 0:
        #     # Checkout time is zero, immediately complete the checkout
        #     customer = line.first_in_line()
        #     # line.remove_front_customer()
        #     events.append(CheckoutCompleted(self.timestamp, line_number, customer))
        if line.is_open:
            # Schedule a CheckoutCompleted event in the future
            customer = line.first_in_line()
            completion_timestamp = self.timestamp + checkout_time
            events.append(CheckoutCompleted(completion_timestamp, line_number, customer))
            # line.remove_front_customer()
        # customer = line.first_in_line()
        # if store.first_in_line(line_number) is customer:
        #     events.append(CheckoutCompleted(self.timestamp + customer.item_time(), line_number, customer))

        return events


class CheckoutCompleted(Event):
    """A customer finishes the checkout process.

    Attributes:
    - line_number: The number of the checkout line where a customer
      is finishing.
    - customer: The finishing customer.
    """

    timestamp: int
    line_number: int
    customer: Customer

    def __init__(self, timestamp: int, line_number: int, c: Customer) -> None:
        """Initialize a CheckoutCompleted event."""
        Event.__init__(self, timestamp)
        self.timestamp = timestamp
        self.line_number = line_number
        self.customer = c

    def do(self, store: GroceryStore) -> list[Event]:
        """Perform this CheckoutCompleted event as specified in the A1 handout,
        and return any events generated by doing so.
        """
        events = []
        line_number = self.line_number
        customer = self.customer

        # Remove the finishing customer from the checkout line
        store.remove_front_customer(line_number)

        # Check if there is a next customer in line
        next_customer = store.first_in_line(line_number)

        # try to run customer arrive if the next customer is none
        # to get them to start checkout in this timestamp
        # if next_customer is None:
        # events.append(CustomerArrival(self.timestamp, next_customer))
        if next_customer:
            # Create a new CheckoutStarted event for the next customer
            events.append(CheckoutStarted(self.timestamp, line_number))
        else:
            pass

        return events


class CloseLine(Event):
    """A CheckoutLine gets closed.

    Attributes:
    - line_number: The number of the checkout line.
    """

    timestamp: int
    line_number: int

    def __init__(self, timestamp: int, line_number: int) -> None:
        """Initialize a CloseLine event."""
        Event.__init__(self, timestamp)
        self.timestamp = timestamp
        self.line_number = line_number

    def do(self, store: GroceryStore) -> list[Event]:
        """Perform this CloseLine event as specified in the A1 handout,
        and return any events generated by doing so.
        """
        events = []
        line_number = self.line_number
        closed_customers = store.close_line(line_number)
        for closed_customer in closed_customers:
            events.append(CustomerArrival(self.timestamp, closed_customer))

        # Removes the line so that you cannot join it anymore
        # store.lines.pop(line_number)

        return events


EVENT_SAMPLE = StringIO(
    """121 Arrive William Bananas 7
22 Arrive Trevor Flowers 22 Bread 3 Cheese 3 Cheese 3
41 Close 0"""
)


def create_event_list(event_file: TextIO) -> list[Event]:
    """Return a list of Event objects to represent the events in <filename>.

    The events in the list must be in the same order as they are in the file.

    Preconditions:
    - <event_file> is open.
    - <event_file> is in the format specified by the assignment handout.

    >>> samp_events = create_event_list(EVENT_SAMPLE)
    >>> len(samp_events) == 3
    True
    >>> isinstance(samp_events[0], CustomerArrival)
    True
    >>> isinstance(samp_events[1], CustomerArrival)
    True
    >>> isinstance(samp_events[2], CloseLine)
    True
    """
    events = []

    for line in event_file:
        parts = line.strip().split()

        # Extract timestamp and event type
        timestamp = int(parts[0])
        event_type = parts[1]

        if event_type == 'Arrive':
            # Create CustomerArrival event
            customer_name = parts[2]
            items = []
            for i in range(3, len(parts), 2):
                item_name = parts[i]
                item_time = int(parts[i + 1])
                item = Item(item_name, item_time)
                items.append(item)
            customer = Customer(customer_name, items)
            event = CustomerArrival(timestamp, customer)

        elif event_type == 'Close':
            # Create CloseLine event
            line_number = int(parts[2])
            event = CloseLine(timestamp, line_number)
        else:
            raise ValueError(f"Unknown event type: {event_type}")

        events.append(event)

    return events


if __name__ == '__main__':
    import doctest

    doctest.testmod()

    check_pyta = True
    if check_pyta:
        import python_ta

        python_ta.check_all(
            config={
                'allowed-import-modules': [
                    '__future__',
                    'typing',
                    'store',
                    'python_ta',
                    'doctest',
                    'io',
                ]
            }
        )
